deployment_package_name: 'deployment-package.zip'
lambda_role_arn: 'arn:aws:iam::971193568016:role/lambda_with_S3_Dynamo_VPC_ForCimpressShopfloor'
s3:
  lambda:
    bucket: 'lambda-deployment-bucket'
    key: 'lambda/deployment/deployment-package.zip'
  secrets:
    bucket: 'secrets-bucket'
    key: 'secrets/key.zip'
  swagger
    bucket: 'swagger-spec-bucket'
    key: 'key/swagger.yaml'
  importer:
    bucket: 'importer-bucket'
    key: 'importer/key.jar'
subnet_ids:
  - 'subnet-fa98c1bc'
  - 'subnet-c09f8da2'
  - 'subnet-daefd0ae'
security_groups:
  - 'sg-b3455cd1'
functions:
  - name: 'FunctionOne'
    handler: 'function_one.handler'
    description: "Function One Description"
    timeout: 30
    memory_size: 512

  - name: 'FunctionTwo'
    handler: 'function_two.handler'
    description: "Function Two Description"
    timeout: 5
    memory_size: 128
